// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAoylgH3TtHj6OjGJV-9EUvKup01Eb5ng',
    appId: '1:240894999884:web:b641962ff59ff0e8a1a3e9',
    messagingSenderId: '240894999884',
    projectId: 'purple-basket',
    authDomain: 'purple-basket.firebaseapp.com',
    storageBucket: 'purple-basket.firebasestorage.app',
    measurementId: 'G-PVNVWCFD6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJwF2kngnX-Y2lQ91YULCSYUO3FzK10xw',
    appId: '1:240894999884:android:462101addba757dda1a3e9',
    messagingSenderId: '240894999884',
    projectId: 'purple-basket',
    storageBucket: 'purple-basket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwJ0ihDc0CGR732vpIxevHPRAZ9poy_lk',
    appId: '1:240894999884:ios:364397cc349fa897a1a3e9',
    messagingSenderId: '240894999884',
    projectId: 'purple-basket',
    storageBucket: 'purple-basket.firebasestorage.app',
    iosBundleId: 'com.example.flutterPurpleBasket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwJ0ihDc0CGR732vpIxevHPRAZ9poy_lk',
    appId: '1:240894999884:ios:364397cc349fa897a1a3e9',
    messagingSenderId: '240894999884',
    projectId: 'purple-basket',
    storageBucket: 'purple-basket.firebasestorage.app',
    iosBundleId: 'com.example.flutterPurpleBasket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAoylgH3TtHj6OjGJV-9EUvKup01Eb5ng',
    appId: '1:240894999884:web:fb7431d516e23e81a1a3e9',
    messagingSenderId: '240894999884',
    projectId: 'purple-basket',
    authDomain: 'purple-basket.firebaseapp.com',
    storageBucket: 'purple-basket.firebasestorage.app',
    measurementId: 'G-WYXEMPLE8E',
  );
}
